# Generated by Django 5.0.3 on 2026-04-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaitem',
            name='reactions',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='cries',
            field=models.IntegerField(default=0, verbose_name='😢'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='fires',
            field=models.IntegerField(default=0, verbose_name='🔥'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='hearts',
            field=models.IntegerField(default=0, verbose_name='❤️'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='laughs',
            field=models.IntegerField(default=0, verbose_name='😂'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='👍'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='user_reactions',
            field=models.JSONField(default=dict, verbose_name='Реакции пользователей'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='wows',
            field=models.IntegerField(default=0, verbose_name='😮'),
        ),
    ]
