# Generated by Django 5.0.3 on 2026-04-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='reactions',
            field=models.JSONField(default=dict, verbose_name='Реакции'),
        ),
    ]
